./gameboy BROKER CAUGHT_POKEMON 1 OK
./gameboy BROKER CAUGHT_POKEMON 1 FAIL
./gameboy BROKER CATCH_POKEMON Pikachu 2 3
./gameboy BROKER CATCH_POKEMON Squirtle 5 2
./gameboy BROKER CATCH_POKEMON Onyx 4 5
./gameboy SUSCRIPTOR CAUGHT_POKEMON 4
./gameboy BROKER CATCH_POKEMON Charmander 4 5